### ISSUE TITLE
Polyfilled <details> doesn't open with enter key in IE

### ISSUE THREAD

**Issue by axemonkey** [alphagov/govuk_elements#277] opened 2016-07-25 14:19 UTC
Reported by the DAC in Wales during accessibility testing of MOJ's Help with fees application.

Keyboard users (in this case a blind tester) expect to be able to tab through forms and interact with each element in the form using only the keyboard. When they tab to a `<details>` element which has been enhanced by [the details polyfill from Elements](https://github.com/alphagov/govuk_elements/blob/master/public/javascripts/vendor/details.polyfill.js) using IE (or JAWS, which uses IE underneath) the user expects to be able to open the `<details>` panel using the enter/return key, but this submits the parent `<form>` instead.

The user is able to expand the panel using the space bar, but not the enter or return keys as they expect. This is only the case in IE – Chrome and Firefox work as expected.

**Comment by selfthinker** [comment] 2016-08-31 16:16
Not 100% the same but related: #130

**Comment by robinwhittleton** [comment] 2016-09-08 13:51
I can’t replicate this with current elements in IE8-11; both the space and enter keys trigger the correct behaviour. I do remember replicating this when you first reported it though. @axemonkey : can you test current elements and see if it’s still a problem? If it is, can you provide a test URL?

**Comment by gemmaleigh** [comment] 2016-10-06 15:57
Also: https://github.com/hmrc/assets-frontend/issues/675

**Comment by robinwhittleton** [comment] 2016-12-12 15:16
Dupe of #130.

**Closed by robinwhittleton** 2016-12-12 15:16 UTC
Labels: bug

**Comment by selfthinker** [comment] 2017-03-23 19:46
I found the reason and we'll hopefully fix it soon. See my comment on https://github.com/alphagov/govuk_elements/issues/130#issuecomment-288837541
