### ISSUE TITLE
Highlight box colour contrast too low for WCAG AA

### ISSUE THREAD

**Issue by maxf** [alphagov/govuk_elements#200] opened 2016-03-21 17:22 UTC
Highlight boxes (as visible at the bottom of https://govuk-elements.herokuapp.com/colour/ ) have a too low colour contrast (3.17) to comply with WCAG2 level AA.
Offending line is:
https://github.com/alphagov/govuk_elements/blob/master/public/sass/elements/_components.scss#L7
Suggest: #0c857b as the nearest colour that satisfies the requirement

**Comment by sanjaypoyzer** [comment] 2016-04-26 11:40
Isn't this only an issue if the colour is used directly on a white background? Is there an example (apart from the swatch) where this is done?

For the swatch, we should probably be putting a border around the element as with the white swatch.

**Comment by gemmaleigh** [comment] 2016-04-26 17:55
Two examples spring to mind:

1. The GOV.UK Bank Holidays page
https://www.gov.uk/bank-holidays

2. The "Confirmation page" pattern
http://govuk-prototype-kit.herokuapp.com/examples/confirmation-page

Both use `#28a197`, or `$turquoise`.

Both examples use white text on the turquoise background.

Since it passes AAA for large text and the smallest font size for the text on this colour on the Bank Holiday page is 18px (for smaller viewports) and 24px (for wider viewports), I'd be keen to keep the background colour the same and add guidance to ensure that text used on this background colour isn't ever smaller than 18px or 14px bold.

--

Foreground: #FFFFFF - Background: #28A197

The contrast ratio is: 3.17:1

Text failed at level AA
Text failed at level AAA

**Large text passed at level AA**
Large text failed at level AAA

1.4.3 Contrast (Minimum):  Text (and images of text) have a contrast ratio of at least 4.5:1, except if the text is pure decoration.  Larger scale text (at least 18 point or 14 point bold) or images of text can have a contrast ratio of 3:1. (Level AA)

1.4.6 Contrast (Enhanced): Text (and images of text) have a contrast ratio of at least 7:1, except if the text is pure decoration.  Larger scale text (at least 18 point or 14 point bold) or images of text can have a contrast ratio of 4.5:1. (Level AAA)

Note: Fonts that are extraordinarily thin or decorative are harder to read at lower contrast levels.

**Comment by sanjaypoyzer** [comment] 2016-04-27 10:45
Ah, sorry I misunderstood - I thought we were talking about `$highlight-colour`.

In the case of the turquoise boxes, I agree that if it passes AAA with large text, we should make that clear in the guidance.

**Comment by edwardhorsford** [comment] 2016-04-27 10:54
I wonder whether those highlight boxes could be done with $govuk-blue instead - is there a reason it should be turquoise? The blue gives a contrast of 6.68:1. cc @joelanman @markhurrell 

$govuk-blue is also used by some services for introduction walk-throughs (verify, passports, notify), but I don't know if it's necessary for it to be different.

![screen shot 2016-04-27 at 11 52 31](https://cloud.githubusercontent.com/assets/2204224/14850091/a89e178a-0c6e-11e6-89da-56cffd308d74.png)

**Comment by sanjaypoyzer** [comment] 2016-04-27 10:57
@edwardhorsford I think there is value in using a different colour here. It gives a sense of "something different is happening now" which could help people feel certain they've reached the end of the interaction. Keen to hear what other people think though.

**Comment by joelanman** [comment] 2016-04-27 10:57
there's something to be said for the green tinge being associated with success, on transaction complete screens, which is important

**Comment by markhurrell** [comment] 2016-04-27 13:42
I'd like to rationalise this to blue for information highlighting (eg, bank holidays, verify and passports etc) and turquoise for completion states (matching the start buttons?)

probably good to look at the typography we use on them too - only 16px+ sizes, and maybe only bold too?

**Comment by joelanman** [comment] 2016-04-27 14:46
@markhurrell start buttons are green no? You think they should be the start button green instead of turquoise?

**Comment by sanjaypoyzer** [comment] 2016-04-27 15:34
@markhurrell Yep, added guidance around font size in the above PR.

The idea of turquoise == completion is interesting. In this prototype that Harry's working on, he shows the user the result of the last bit of the transaction (finding the licence) using the turquoise box, before sending them onto the next bit of the transaction (updating their details). Do you think this is a good example of a box that should be blue, because the user hasn't finished what they were trying to do? Or is it okay to use the completion colour to mark completion of a *bit*?

<img width="795" alt="screen shot 2016-04-27 at 16 27 49" src="https://cloud.githubusercontent.com/assets/4106955/14857822/86d91920-0c95-11e6-8ffe-f2516ea4a467.png">

**Comment by edwardhorsford** [comment] 2016-04-27 15:44
In general I think I'm seeing too much of the turquoise box. I'm seeing it used in other contexts like notifications too, which I think we could have a different pattern for.

**Comment by sanjaypoyzer** [comment] 2016-04-28 08:58
Yeah, in the guidance it's called a "highlight box" which is pretty generic. If we called it a "success box" or something, then we could constrain the usage a bit more. Then we could add new patterns for those uses.

I'm guessing at this point we just have to swallow the fact that there are services out there already which will then not be following the new patterns?

**Comment by edwardhorsford** [comment] 2016-04-28 11:23
Playing with an idea @timpaul had. I don't know if I like it, but that might be because it looks so different to me.

This uses a slightly darker turquoise for the non-bold text, and regular turquoise for everything else.
![screen shot 2016-04-28 at 12 19 59](https://cloud.githubusercontent.com/assets/2204224/14884296/ae8f0e38-0d3b-11e6-9f38-72b804844bd4.png)

**Comment by markhurrell** [comment] 2016-04-28 12:04
@edwardhorsford yeah I'm not sure about that one. feels like it would have way less impact (especially on mobile)

tbh I'd prefer if we thought about this a bit more systematically. we should be thinking about how coloured boxes work across verify and passports too, and what colours we use for what purpose

**Comment by cjforms** [comment] 2016-04-28 15:44
I am much happier with this version than with the current reversed-polarity one. Reversed-polarity worries me because:
1. What happens when the user elects to reverse the polarity or tune the basic colour scheme? Does it reverse again? If so, can the person actually read it if they need a different colour scheme in the first place?
2. I've seen lots of instances where reversed-polarity elements work excellently as graphic elements in the page (in this case 'something big happened') but where the reversed-polarity seems to have the ability to suck the content out of the element, as if it became a pure graphic with no content in it. 

I like this version because it has Big Important Text with the standard polarity.

(I'm not quite so keen on the box part. I suspect it might suffer from the 'boxed warning' problem that's been discovered in testing of patient information leaflets, the compulsory leaflets that come with medicines. The counter-intuitive finding is that boxed warnings are actually less likely to be read than the ordinary text that doesn't have a box around it; it seems to be a similar problem to the  banner-blindness and ad-blindness phenomena that we know about on the web).

**Comment by markhurrell** [comment] 2016-04-28 16:11
@cjforms hey caroline - if we have it as ed's idea without the box, it's pretty much just normal text on the page. 

the big boxes for that type of information work effectively, I don't think there's a reason for ditching them. we just need to make sure we aren't causing any contrast issues (and probably consider making them a bit more consistent)

**Comment by edwardhorsford** [comment] 2016-04-28 16:13
I've seen the existing boxes work very well in user research.

(also - it's Tim's idea - just sharing for discussion)

**Comment by cjforms** [comment] 2016-04-28 16:18
@markhurrell, not exactly. It's giant centred text in a distinctive colour and layout that's different to what's happened before. 

@edwardhorsford yes, I've seen these reversed-polarity elements work very well as graphic elements to signal 'something different has happening here'. 
The problem I'm trying to articulate is that I've observed that users can fail to understand and act on the content that sits within the element. For example, they may grasp the message 'the computer dealt with the thing I just completed' (signified by the big change in layout) but fail to see that there's an important reference number placed on the box.

**Comment by stephenjoe1** [comment] 2016-04-28 16:33
I would be sceptical about changing the current confirmation page layout with the big turquoise block at the top. During pay user research this page has tested very well. Pretty much every participant has noted the message and reference number. If we make the turquoise colour slightly darker for better contrast that's fine but I don't think we need to do anything else.

**Comment by joelanman** [comment] 2016-04-28 16:39
+1 to making the turquoise (or similar colour) box specifically "transaction success messaging", and making the tick part of that pattern, to not rely on colour so much

**Comment by cjforms** [comment] 2016-04-28 16:41
@stephenjoe1 
That's good. 
Have you tried it with anyone who needs to use a reversed colour scheme because of reading difficulties such as dyslexia?
Do you know why some / any participants didn't note the reference number?

**Comment by sanjaypoyzer** [comment] 2016-05-18 11:06
Me and Richard Morton had a bit of chat about this yesterday, and unstuck it a little bit.

Something that makes it quite difficult is that the AA guidelines specify font size in `points` rather than `pixels`. There is a notion that 1 point = 1.33 pixels, which means when AA wants 18pt, we should be using 24px.

(How this 1pt / 1.33px conversion translates to smaller screens, which are often held closer to the face, is unclear... But unless we do our own research to work that out, or W3C come out with guidelines that work better for a world of various screens, AA is the best guidelines we have.)


So if we stick with `#28A197`, we have to use at least 24px, or 19px bold.

Right now the example on smaller screens:

`.bold-large` (24px bold) - passes AA
`p` (16px) - fail
`.heading-medium` (18px bold) - almost passes, should 1px bigger

<img width="339" alt="screen shot 2016-05-18 at 11 00 20" src="https://cloud.githubusercontent.com/assets/4106955/15356298/d9f5d5d4-1cef-11e6-8040-4050aa4a1661.png">

If we increase the `.heading-medium` by 1px, and also use it on the `p` we have: 

<img width="341" alt="screen shot 2016-05-18 at 11 58 10" src="https://cloud.githubusercontent.com/assets/4106955/15356324/f94681d6-1cef-11e6-98ec-629f901d2de4.png">

Arguably that makes the header disappear though, so we could bump that up to `.heading-xlarge`:

<img width="332" alt="screen shot 2016-05-18 at 12 01 00" src="https://cloud.githubusercontent.com/assets/4106955/15356396/540efda0-1cf0-11e6-8820-61000bb6adff.png">

And on a bigger screen:

<img width="978" alt="screen shot 2016-05-18 at 12 03 49" src="https://cloud.githubusercontent.com/assets/4106955/15356448/a31c3368-1cf0-11e6-824d-27fc082b2968.png">

Should probably be played with a little bit more, but I think if we don't want to change the colour and we want to pass AA, then we need to be heading in this direction. Keen to hear what people think.

**Comment by joelanman** [comment] 2016-05-18 11:14
It looks nice, but I'd worry that, especially with a longer service name or smaller screen, this larger design is more likely to take over the whole screen. This might make it more likely for people to think that's all there is, and not know to scroll.

Is another alternative to investigate a darker green?

**Comment by sanjaypoyzer** [comment] 2016-05-18 11:42
Yeah, I think a darker green needs to be investigated. I found [a tool to help find alternatives](http://contrast-finder.tanaguru.com/result.html?foreground=%23FFFFFF&background=%2328A197&algo=Rgb&ratio=4.5&isBackgroundTested=true) but the suggestions it gives are quite dull. 😞

**Comment by markhurrell** [comment] 2016-05-18 12:24
I'd like to find a better solution than just using dull colours

there's only a very narrow bandwidth of colour that passes colour contrast
against both black and white




Mark Hurrell
Head of Design for GOV.UK
Government Digital Service

**Comment by sanjaypoyzer** [comment] 2016-05-18 12:45
@markhurrell What are your thoughts on the bigger and bolder text?

**Comment by markhurrell** [comment] 2016-05-18 12:57
i like the bigger, bolder text

wonder what the average ref number length is. could we make that bit bigger




Mark Hurrell
Head of Design for GOV.UK
Government Digital Service

**Comment by sanjaypoyzer** [comment] 2016-05-18 13:42
Sure -

<img width="331" alt="screen shot 2016-05-18 at 14 36 14" src="https://cloud.githubusercontent.com/assets/4106955/15360560/f8544342-1d05-11e6-9c9c-10ba769eff12.png">

<img width="984" alt="screen shot 2016-05-18 at 14 37 43" src="https://cloud.githubusercontent.com/assets/4106955/15360609/1ef83134-1d06-11e6-90c0-6a4946c93cfd.png">

If we're happy with that, I can do a PR for it and include some text about making sure text is big when using that colour. I'll think I'll leave `.heading-medium` at 18px rather than bumping it up 1px as I'm sure that will have much more far reaching effects.

**Comment by edwardhorsford** [comment] 2016-05-18 13:52
Would be good to keep in mind that some services have quite a bit more text in this box. We're currently only testing with the simplest case. Perhaps collect some examples of summary boxes?

For the proposed solution:
I'm wary of relying on specific guidance about font weights and sizes - I would anticipate in many cases services will just pick what seems suitable to them.

**Comment by joelanman** [comment] 2016-05-18 15:07
The pattern was originally designed for very little content. We should definitely collect examples of use, but also assess whether, if there is more content, that's a thing we should endorse or advise against.

**Comment by cjforms** [comment] 2016-05-18 22:26
+1 to @joelanman on collecting examples. 

Quick reminder: I still haven't had an answer to my question about how this box behaves for people who elect to reverse foreground and background. Does it stay the same, reverse, or disappear?

**Comment by accessiblewebuk** [comment] 2016-05-19 11:08
@markhurrell Does this need to work against both black and white text?

**Comment by joelanman** [comment] 2016-05-19 11:39
@cjforms on OSX, this is close to "invert colours" set in system preferences:

![image](https://cloud.githubusercontent.com/assets/1132904/15392367/915a7e40-1dbe-11e6-804a-2efa22ff4452.png)

(I had to edit the colours by hand as taking a screenshot doesn't work - it takes a screenshot of the non-inverted colours)

**Comment by robinwhittleton** [comment] 2016-11-09 15:39
@edwardhorsford @joelanman what was the action out of this then? Was it to specifically recommend only using bold text on http://govuk-elements.herokuapp.com/colour/#examples ? Do we want to specifically darken the turquoise to cope with whatever fonts the consuming developer chooses to use?

**Comment by edwardhorsford** [comment] 2016-11-09 15:54
I think no clear action as yet. In the short term we can recommend bold and larger font sizes.

Should gather together some options and discuss. I've spoken with @timpaul before about setting up some kind of 'board' to make decisions on awkward things like these.

**Comment by selfthinker** [comment] 2017-03-24 16:27
To fully answer @cjforms' question. For people who don't fully invert the screen but change colours via either browser settings or Windows system settings, the box completely disappears. I'm not sure if that's a problem, though, as they will be used to it and it probably still looks different enough to stand out.

I tested with changing colours in Firefox and switching to the first Windows 'High Contrast' colour scheme and looked in Edge. Both look nearly identical which is why I only attach one screenshot:

<img width="604" alt="highlight-box-firefox-with-changed-colours" src="https://cloud.githubusercontent.com/assets/108893/24303490/1d7708f2-10ae-11e7-8493-558516d9b01b.png">

I guess it could be fixed in a [similar way we fixed buttons](https://github.com/alphagov/govuk_frontend_toolkit/pull/377), by giving the box an invisible outline. When you do that, it looks like this (and would be invisible otherwise):

<img width="626" alt="highlight-box-firefox-with-changed-colours-and-transparent-outline" src="https://cloud.githubusercontent.com/assets/108893/24303618/95f3ed04-10ae-11e7-9943-10707ff43dc1.png">

**Comment by accessiblewebuk** [comment] 2017-03-28 11:24
Just to clarify that from a WCAG point of view, we only need to consider the colour contrast in a typical setup - not with changes by assistive technology (e.g. Zoomtext) or changes to browser or OS colour settings. To quote from https://www.w3.org/TR/UNDERSTANDING-WCAG20/visual-audio-contrast-contrast.html :

Note 6: WCAG conformance should be evaluated for colour pairs specified in the content that an author would expect to appear adjacent in typical presentation. Authors need not consider unusual presentations, such as colour changes made by the user agent, except where caused by authors' code.

**Comment by accessiblewebuk** [comment] 2017-03-28 11:31
If we want the highlighting colour to be bright then we can't use white or very pale text, unless we do things like outlining the text with a dark colour. The existing turqoise would work fine with darker text - the only question is whether that gives the same impact? 

![light text](https://cloud.githubusercontent.com/assets/18284458/24402896/6ba6c16e-13b2-11e7-9e69-03b0307ae092.png)
![dark text](https://cloud.githubusercontent.com/assets/18284458/24402897/6e6b0194-13b2-11e7-8b9b-927f150db6b9.png)

**Comment by accessiblewebuk** [comment] 2017-03-28 12:29
Example of what I meant about outlining the text (but I don't know how well this is supported cross browser or for older browsers: 
![stroke text](https://cloud.githubusercontent.com/assets/18284458/24404795/82c7c980-13ba-11e7-80d9-2b264d7c2ce1.png)

**Comment by robinwhittleton** [comment] 2017-03-28 13:00
You could do it with `text-stroke` [in Webkit / Blink and recent Firefox / Edge](http://caniuse.com/#feat=text-stroke). Alternatively you could use `text-shadow` which would look somewhat different but might work just as well: that’s [well supported](http://caniuse.com/#feat=css-textshadow) (we’d only be not showing it for IE8/9 and that’s probably acceptable at this point).

**Comment by alextea** [comment] 2017-03-28 13:45
Personally I think the pattern should dictate the font weight and size. We don't want it to be used for body copy. The purpose for the pattern is to highlight confirmation.

**Comment by accessiblewebuk** [comment] 2017-03-28 14:30
This example has text-stroke for the date and text-shadow for the rest of the text:

![text shadow](https://cloud.githubusercontent.com/assets/18284458/24410615/69c4e79a-13cb-11e7-8b23-9273bb729da2.png)

**Comment by joelanman** [comment] 2017-03-28 14:44
Is there a problem with @gemmaleigh 's suggestion? It sounds good to me:

> Since it passes AAA for large text and the smallest font size for the text on this colour on the Bank Holiday page is 18px (for smaller viewports) and 24px (for wider viewports), I'd be keen to keep the background colour the same and add guidance to ensure that text used on this background colour isn't ever smaller than 18px or 14px bold.

**Comment by accessiblewebuk** [comment] 2017-03-28 14:56
@joelanman this has come up earlier in the discussion: 

The WCAG guidelines are for 14pt bold text and 18pt standard text - it is generally agreed that the conversion factor between pt and px for these purposes should be one and a third so the minimum size to be classed as large text is 19px bold or 24px standard text.

**Comment by joelanman** [comment] 2017-03-28 14:58
@accessiblewebuk sorry - missed it, so that sounds like something we could consider recommending? 19px bold or 24px standard at minimum

**Comment by accessiblewebuk** [comment] 2017-03-28 15:46
@joelanman those sizes would pass - if that is the simplest way of getting this resolved then I am all for it - it may well depend on other factors though like how much text might be needed. 

Interestingly the Bank Hol example I posted is already 24px for the smaller text size. The application complete example isn't though so here is a before and after: 

![light text](https://cloud.githubusercontent.com/assets/18284458/24414347/179425a2-13d6-11e7-91d9-9dd50d6abfff.png)
![24px](https://cloud.githubusercontent.com/assets/18284458/24414355/1c0787dc-13d6-11e7-9963-a5ed954a17ab.png)

**Comment by joelanman** [comment] 2017-03-28 15:52
Looks good to me

**Comment by sanjaypoyzer** [comment] 2017-03-29 08:56
lol that's exactly what i posted on the 18th May last year 😉

**Comment by joelanman** [comment] 2017-03-29 09:04
Oh yeah and there's relevant discussion on that point too, about whether people would just use a smaller font anyway, and about gathering examples of usage. I think this is more evidence we could do with more people/time to look at patterns.

**Comment by sanjaypoyzer** [comment] 2017-03-29 09:08
But then as Alex has said above, the pattern could/should dictate what kind of text is used in it.

**Comment by edwardhorsford** [comment] 2017-03-29 09:35
We should aim for a solution that has 4.5:1 contrast and doesn't rely on teams getting it right. We aim for that everywhere else - why is this any different?

We can try to dictate what kind of text is used, but in practice teams can and will modify it. Aiming for 4.5:1 means we're good no matter what.

I'm not clear why the pattern is using turquoise - or the significance of it. 

If there is no semantic meaning, I suggest going with `$govuk-blue`.
![screen shot 2017-03-29 at 10 31 48](https://cloud.githubusercontent.com/assets/2204224/24448106/f514666e-146a-11e7-8007-9df065c6cb26.png)

If there is semantic meaning, how about a stronger green?
![screen shot 2017-03-29 at 10 31 12](https://cloud.githubusercontent.com/assets/2204224/24448170/2623010c-146b-11e7-94a8-4b6679b502b9.png)

**Comment by joelanman** [comment] 2017-03-29 11:08
The semantic meaning here is success, and in my experience the turquoise box has always tested well. I think we'd have to test the blue and green to make sure it's ok, and the green could possibly clash with a button on the same page.

**Comment by joelanman** [comment] 2017-03-29 11:09
Bank holiday is different - being just information. Maybe that would work just as blue, the same as our 'intro slides' pattern.

**Comment by sanjaypoyzer** [comment] 2017-03-29 11:22
@joelanman Surely there shouldn't be any buttons on such a page?

**Comment by joelanman** [comment] 2017-03-29 11:28
@sanjaypoyzer don't see why not, if there's a common action to do next having finished that one. Maybe it's common to make a second application, or another service?

**Comment by edwardhorsford** [comment] 2017-03-29 11:30
Having a button on the page is a common pattern. It might be to do something else, or to return to GOV.UK or to give feedback.

With that said, I'd be really surprised if moving to a greener green caused any issues.

**Comment by accessiblewebuk** [comment] 2017-04-12 09:19
Who can make a decision on the way forward with this?

**Comment by selfthinker** [comment] 2017-04-12 11:31
@markhurrell can make that decision. And because this has been going back and forth for so long, I'd suggest he should do that.

**Comment by markhurrell** [comment] 2017-04-12 13:22
@selfthinker  👌🏼

for the moment, we should just recommend only using 19px and larger on these boxes

looking at the bank holidays page etc is part of the GOV.UK template consolidation team's work, so the design might end up being iterated pretty soon anyway. i'll add this to the design considerations of that work

If/when we do update the bank holiday page design, we should look at incorporating those changes to the confirmation page pattern

**Comment by joelanman** [comment] 2017-04-12 13:42
apparently it's 19px bold or 24px standard to pass standards

**Comment by accessiblewebuk** [comment] 2017-04-12 14:08
@markhurrell 

To compare options 1) as it currently is (fail):
![unchanged](https://cloud.githubusercontent.com/assets/18284458/24961763/c4d434b6-1f91-11e7-8b02-fe30761ffb2b.png)

2) 19px bold text (pass):
![19px bold](https://cloud.githubusercontent.com/assets/18284458/24961790/d9745c84-1f91-11e7-81f0-5ad618689d19.png)

3) 24px normal text (pass): 
![24px](https://cloud.githubusercontent.com/assets/18284458/24961801/e80d75d2-1f91-11e7-9542-0ef5c001db4e.png)

**Comment by gemmaleigh** [comment] 2017-04-12 16:44
Thanks all for the detailed discussion and to @selfthinker and @accessiblewebuk for reminding us to resolve this. The simplest solution seems to me to increase the size of the text (hat tip to @sanjaypoyzer). I've increased the size of the text over in #451, @markhurrell has approved it. Thanks everyone!

**Closed** 2017-04-12 16:46 UTC
