### ISSUE TITLE
iOS requires double click on <summary> element to expand details

### ISSUE THREAD

**Issue by lukasz-kaniowski** [alphagov/govuk_elements#401] opened 2017-02-08 15:00 UTC
If you try to expand `<details>` element on iOS you need to click twice. 
Problem exists on safari and chrome in iOS

Try expand `Help with nationality` here https://govuk-elements.herokuapp.com/typography/#typography-hidden-text

**Comment by nickcolley** [comment] 2017-02-09 17:12
Hey @lukasz-kaniowski :)

I'm having trouble reproducing this, can you let me know as much as you can about the devices you're using to reproduce this? For example: iOS version, Safari version (if possible)

Thanks 👍

**Comment by lukasz-kaniowski** [comment] 2017-02-10 09:33
@nickcolley It's happening only if element is out of focus (i.e. straight after you enter the page), check the [video](http://sendvid.com/2xxknfw6) for details

chrome: 56.0.2924.79
iOS: 10.2.1

**Comment by nickcolley** [comment] 2017-02-10 11:31
We don't have native devices but I've managed to reproduce in a simulated iOS 10 on browserstack!

Thanks for the report 👍

**Comment by lukasz-kaniowski** [comment] 2017-02-10 11:50
Np, any idea what may be causing this behaviour?

**Comment by nickcolley** [comment] 2017-02-10 11:56
Not sure at this point, if I get some downtime I'll have a look into it sorry!

My suspicion is around the use of `mouseup` https://github.com/alphagov/govuk_elements/blob/master/public/javascripts/govuk/details.polyfill.js#L46 which could be behaving oldly.

I'd investigate that alongside potential use of [pointer events](https://developer.mozilla.org/en-US/docs/Web/API/Pointer_events) and [touch events](https://developer.mozilla.org/en/docs/Web/API/Touch_events)

**Comment by theleebriggs** [comment] 2017-02-10 13:27
Had a quick look, with JS disabled I can reproduce it, seems to come down to a combination of `cursor: pointer;` on the `<summary>` along with the nested `<span>` - remove the cursor declaration and it goes away OR remove the span and leave the style also fixes. 

https://github.com/alphagov/govuk_elements/blob/master/public/sass/elements/_details.scss#L11

Interestingly I think the `<span>` is only there to control `text-decoration` on hover when the element has been polyfilled to give it a `twisty` arrow.

I'll keep looking when I have a chance, but I'm thinking it's not a JS issue.

**Comment by lukasz-kaniowski** [comment] 2017-02-13 16:17
I've done some more digging. In my situation it seems to be caused by `.panel` class inside of the details div. More precisely something from `@extend %contain-floats;`

**Comment by gemmaleigh** [comment] 2017-02-13 16:42
Hi @lukasz-kaniowski - thanks for letting us know!

If it helps you in the meantime - the `%contain-floats` placeholder is coming from the [govuk_frontend_toolkit's _shims.scss file](https://github.com/alphagov/govuk_frontend_toolkit/blob/e03e7f56e1b70194310ee970a3ccf00bd9376b36/stylesheets/_shims.scss#L45).

**Comment by lukasz-kaniowski** [comment] 2017-02-13 17:27
More digging. Once I've commented out hover section https://github.com/alphagov/govuk_elements/blob/master/public/sass/elements/_details.scss#L15 all start to work as expected.
Now the question is, can I override this in sass file that imports govuk_elements? 
Or maybe we could target this with media queries only to browsers?

**Comment by alex-ju** [comment] 2017-07-13 11:14
Hi @lukasz-kaniowski. I am unable to reproduce this on iOS 10.3 and iOS 9. Unfortunately I am not able to test it on iOS 10.2. Can you confirm the bug is still there?

**Comment by selfthinker** [comment] 2017-11-10 18:14
This is another issue which might be fixed with #572?

**Comment by alex-ju** [comment] 2017-11-13 23:47
I got my hands on a phone with an iOS 10.2 and I can confirm the bug is still there:
 - after first click `<summary>` receives focus, but doesn't expand the details
 - on the second click, it expands the details

**Comment by nickcolley** [comment] 2018-09-07 15:11
Following the launch of the GOV.UK Design System, GOV.UK Elements will now only get major bug fixes and security patches.

We have done some investigation using the GOV.UK website's browser statistics to see how many users this is impacting:

| Version | Users in August 2018 | Percentage of iOS users | Percentage of overall users |
| - | - | - | - |
| v10.2 | 181184 | 1.45% | 0.39% |
| v10.3 | 579199 | 4.64% | 1.25% |

(Thanks @36degrees for this data)

Given that this is a low percentage, and that we may try and update the details component in GOV.UK Frontend to avoid polyfilling I'm going to close this out.

See https://github.com/alphagov/govuk-frontend/issues/988

**Closed by nickcolley** 2018-09-07 15:11 UTC
Labels: bug
